apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-backend-deployment
  namespace: beauth
  labels:
    app: auth-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-backend
  template:
    metadata:
      labels:
        app: auth-backend
    spec:
      containers:
      - name: auth-backend-container
        image: ravikishans/streamingapp:backend_auth
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: auth-backend-secrets
              key: MONGO_URI
        # - name: JWT_SECRET
        #   valueFrom:
        #     secretKeyRef:
        #       name: auth-backend-secrets
        #       key: JWT_SECRET
        # - name: AWS_KEY_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: auth-backend-secrets
        #       key: AWS_KEY_ID
        # - name: AWS_SECRET_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: auth-backend-secrets
        #       key: AWS_SECRET_KEY
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: AWS_S3_BUCKET
          value: "rakshi2502"
