apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
  type: {{ .Values.backend.service.type }}
