apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
  type: {{ .Values.frontend.service.type }}
